Feature/create messages
Ayokunnumi1/hello-react-front-end pull request #1
Opened 2024-02-02 22:29 UTC by Ayokunnumi1

These are the project requirement fulfilled in this branch;

Create a new React app called 'hello-react-front-end'
Initialize your project with Git.
Create the App component with react-router.
Create the Greeting component that will display a greeting. Set it up as a route in your App component.
Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
Display the random greeting in your Greeting component.

2024-02-02 22:50 UTC, merged

2024-02-02 23:02 UTC, LionRouge1 requested changes
Hi @Ayokunnumi1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- The two apps work together :heavy_check_mark: 
- Use redux to connect to the API endpoint :heavy_check_mark: 
- `App` component have route that leads to the `Greeting` component :x:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-02 23:02 UTC, LionRouge1 commented on src/App.jsx
> +    <Greeting />
- [ ] Kudos, You have done a great job displaying the greeting from the API endpoint :clap: However, according to the project requirement we should set up a route in the `App` component that leads to the Greeting component. Therefore I suggest that you make a use of **`react-route`** to create a link in the `App` component that link to the **`Greeting`** component to follow the project requirement.
![Screenshot from 2024-02-02 22-49-31](https://github.com/Ayokunnumi1/hello-react-front-end/assets/91142432/cf3eb7ca-bedc-4e92-8a4d-2495f16eb0fc)

2024-02-03 20:16 UTC, Ibizugbe reviewed
Hi @Ayokunnumi1 👋🏼👋🏼, 

![approved](https://github.com/Ayokunnumi1/hello-react-front-end/assets/64643995/6b370d28-239b-4fbf-8172-33461f70e443)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] User interface looks great👍🏼.
- [x] `react-router` has been used👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-03 20:21 UTC, Ayokunnumi1 commented
I mistakenly merged the branch after the first reviewer approved the backend without waiting on his review of the frontend. I have implemented the changes without creating a new pull request